clinica_das_malas/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from clinica_das_malas.accounts.views import register, conta, messages
from clinica_das_malas.settings import LOGOUT_URL

urlpatterns = [
    url(r'^entrar/', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^sair/', logout, {'next_page': LOGOUT_URL}, name='logout'),
    url(r'^cadastre-se/$', register, name='register'),
    url(r'^mensagens/$', messages, name='mensagens'),
    url(r'^$', conta, name ='conta'),
]

clinica_das_malas/bagagem/urls.py
from django.conf.urls import url
from .views import list_bagagens, show_bagagem, entra_bagagem, cliente_bagagens

urlpatterns = [
    url(r'^$', list_bagagens, name="list"),
    url(r'^(\d+)', show_bagagem, name="show"),
    url(r'^entra/$', entra_bagagem, name="entra_bagagem"),
    url(r'^cliente/$', cliente_bagagens, name="cliente"),
]

clinica_das_malas/core/urls.py
from django.conf.urls import url

from clinica_das_malas.core.views import home, contato, send_email


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^contato/$', contato, name='contato'),
    url(r'^index', send_email, name="email"),
]

clinica_das_malas/index/urls.py
from .views import index
from django.conf.urls import url

urlpatterns = [
    url(r'^$', index, name='index'),
    # url(r'^contato/$', contato, name='contato'),
    # url(r'^email', send_email, name="email"),
]

clinica_das_malas/tecnico/urls.py
from django.conf.urls import url

from clinica_das_malas.tecnico.views import historico, pesquisar, geral

urlpatterns = [
    url(r'^(\d+)', historico, name="historico"),
    url(r'^pesquisa', pesquisar, name="pesquisar"),
    url(r'^geral', geral, name="geral")

]

clinica_das_malas/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from clinica_das_malas.core.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^conta/', include('clinica_das_malas.accounts.urls', namespace="accounts")),
    url(r'^', include('clinica_das_malas.core.urls', namespace="core")),
    url(r'^bagagens/', include('clinica_das_malas.bagagem.urls', namespace="bagagem")),
    url(r'^estoque/', include('clinica_das_malas.produto.urls', namespace="produto")),
    url(r'^index/', include('clinica_das_malas.index.urls', namespace="index")),
    url(r'^tecnico/', include('clinica_das_malas.tecnico.urls', namespace="tecnico"))
]

clinica_das_malas/core/models.py
from django.db import models

# Create your models here.

clinica_das_malas/core/forms.py
from django import forms

class FormEmail(forms.Form):
    name = forms.CharField(label='Nome', max_length=50)
    email = forms.EmailField(label='Email')
    mensagem = forms.CharField(label='Mensagem', widget=forms.Textarea)

clinica_das_malas/core/views.py
import json as simplejson
from datetime import datetime, timedelta
from django.shortcuts import render

from clinica_das_malas.bagagem.models import Bagagem
from .forms import FormEmail
from django.core.mail import send_mail


def home(request):

    if request.user.is_authenticated():
        if request.user.is_superuser:
            entrada_total_mes1 = 0
            entrada_total_mes2 = 0
            entrada_total_mes3 = 0
            entrada_total_mes4 = 0
            bagagens_month1 = Bagagem.objects.filter(created_at__month=get_previous_month(0))
            bagagens_month2 = Bagagem.objects.filter(created_at__month=get_previous_month(1))
            bagagens_month3 = Bagagem.objects.filter(created_at__month=get_previous_month(2))
            bagagens_month4 = Bagagem.objects.filter(created_at__month=get_previous_month(3))

            for bagagem in bagagens_month1:
                entrada_total_mes1 += bagagem.get_valor()
            entrada_total_mes1 = simplejson.dumps(entrada_total_mes1)# Viabilizando utilização no js

            for bagagem in bagagens_month2:
                entrada_total_mes2 += bagagem.get_valor()
            entrada_total_mes2 = simplejson.dumps(entrada_total_mes2)# Viabilizando utilização no js

            for bagagem in bagagens_month3:
                entrada_total_mes3 += bagagem.get_valor()
            entrada_total_mes3 = simplejson.dumps(entrada_total_mes3)# Viabilizando utilização no js

            for bagagem in bagagens_month4:
                entrada_total_mes4 += bagagem.get_valor()
            entrada_total_mes4 = simplejson.dumps(entrada_total_mes4)# Viabilizando utilização no js

            context = {'user': request.user,
                       'valor1': entrada_total_mes1,
                       'valor2': entrada_total_mes2,
                       'valor3': entrada_total_mes3,
                       'valor4': entrada_total_mes4}
        else:
            context = {'user': request.user}

        return render(request, 'inicio.html', context)
    else:
        return render(request, 'index.html')


def contato(request):
    context = {}
    return render(request, 'contato.html', context)


def send_email(request):
    template_name = 'index.html'
    context = {}

    if request.method == 'POST':
        form = FormEmail(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            send_mail(
                form.cleaned_data['name'],
                'Nome: ' + form.cleaned_data['name'] + '\n' + 'De: ' + form.cleaned_data['email'] + '\n\n\n' + 'Mensagem: ' + form.cleaned_data['mensagem'],
                form.cleaned_data['email'],
                ['admclinicadasmalas@gmail.com '],
                fail_silently=False,
            )
            form = FormEmail()#Limpando o formulário novamente
    else:
        form = FormEmail()
    context['form'] = form
    return render(request, template_name, context)


def get_previous_month(qtd):
    i=0
    prev = datetime.today()
    for i in range(qtd):
        prev = prev.replace(day=1) - timedelta(days=1)
    print(prev)
    return prev.month

clinica_das_malas/core/templates/contato.html
{% extends 'home.html' %}
{% load static%}
{% block content %}

    <div class="container" style="background: white">
	<div class="row-fluid">
        <div class="span8" style="float: left; width: 60%; margin-top: 1%">
        	<iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1613.980692956285!2d-47.89597371809373!3d-15.818993347038015!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x935a3acce77b49fb%3A0xb1d4f6d578a2c573!2sSapataria+Cl%C3%ADnica+das+Malas!5e0!3m2!1spt-BR!2sbr!4v1490328253371"></iframe>
    	</div>

      	<div class="span4" style="float: right;width: 35%">
    		<address>
                <br>
                <h3><strong>Clínica das Malas</strong></h3><br>
    			407 sul, Bloco C, Loja 22<br>
    			<br>Horário de Funcionamento: De Segunda à Sabado<br>
                Das 08:00 às 18:00<br>
    			<br>Telefone: (61) 3443-7481
    		</address>
            <div style="width: 40%; height: 50%">
                <div style="float: left">
                    <a href="/index/#contact">
                        <img alt="Email" src="{% static 'images/message.jpg' %}">
                    </a>
                </div>
                <div style="float: right">
                    <a href="https://www.facebook.com/clinicadasmalas/">
                        <img alt="Facebook" src="{% static 'images/facebook.jpg' %}">
                    </a> 
                </div>
            </div>
    	</div>
    </div>
</div>

{% endblock content %}

clinica_das_malas/core/templates/email.html
{% extends 'home.html' %}
{% block content %}
{% load widget_tweaks %}
<div class="container">
	<div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well well-sm">
					{% if is_valid %}
				    <div class="alert alert-success" role="alert">Mensagem enviada com sucesso!</div>
				  {% endif %}
					<form class="form-horizontal" action="" method="post">
          <fieldset>
            <legend class="text-center">Contato</legend>

            <!-- Name input-->


						{% csrf_token %}
						<div class="form-group">
							<label class="col-md-3 control-label" for="name">Nome</label>
							<div class="col-md-9">
								{% render_field form.name class+="form-control" placeholder="Nome" %}
								{% if form.name.errors %}
								<div class="alert alert-danger" role="alert">{{form.name.errors}}</div>
								{% endif %}
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-3 control-label" for="name">Seu Email</label>
							<div class="col-md-9">
								{% render_field form.email class+="form-control" placeholder="example@email.com" %}
								{% if form.email.errors %}
								<div class="alert alert-danger" role="alert">{{form.email.errors}}</div>
								{% endif %}
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-3 control-label" for="name">Mensagem</label>
							<div class="col-md-9">
								{% render_field form.mensagem class+="form-control" placeholder="Digite sua mensagem aqui.." %}
								{% if form.mensagem.errors %}
								<div class="alert alert-danger" role="alert">{{form.mensagem.errors}}</div>
								{% endif %}
							</div>
						</div>
            <!-- Form actions -->
            <div class="form-group">
              <div class="col-md-12 text-right">
                <button type="submit" class="btn btn-primary btn-lg"> Enviar </button>
              </div>
            </div>
          </fieldset>
          </form>
        </div>
      </div>
	</div>
</div>
{% endblock content %}

clinica_das_malas/core/templates/home.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Clinica das Malas</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/accounts.css' %}" rel="stylesheet">
    <link href="{% static 'css/list_bagagem.css' %}" rel="stylesheet">
    <link href="{% static 'css/progresso.css' %}" rel="stylesheet">
    <link href="{% static 'css/tecnicos.css' %}" rel="stylesheet">
    <link href="{% static 'css/inicio.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
  {% if user.is_authenticated %}
    <div id="menu">
      <nav class="navbar navbar-default">
        <div class="container-fluid">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'core:home' %}">
                <img alt="Brand" src="{% static 'images/brand.png' %}">
              </a>
            </div>

	  {% if user.e_funcionario == True %}
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Entrada <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'bagagem:entra_bagagem' %}">Cadastrar</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'bagagem:list' %}">Lista de Objetos</a></li>
                </ul>
              </li>
              <li><a href="{% url 'produto:list' %}">Estoque</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Funcionários <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'tecnico:geral' %}">Técnicos - Geral</a></li>
                  <li><a href="{% url 'tecnico:pesquisar' %}">- Histórico</a></li>
                  <li><a href="#">- Formulários</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Caixa - Geral</a></li>
                  <li><a href="#">- Histórico</a></li>
                  <li><a href="#">- Formulários</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Motorista - Geral</a></li>
                  <li><a href="#">- Histórico</a></li>
                  <li><a href="#">- Formulários</a></li>
                </ul>
              </li>
            </ul>
	        <ul class="nav navbar-nav">
				<li><a href="/admin">Administração</a> </li>
			</ul>
		  {% else %}
			  <ul class="nav navbar-nav">
			    <li><a href="{% url 'bagagem:cliente' %}">Meus Produtos</a> </li>
			  </ul>
		  {% endif %}

{#            <form class="navbar-form navbar-left">#}
{#              <div class="form-group">#}
{#                <input type="text" class="form-control" placeholder="Cliente, Número OS...">#}
{#              </div>#}
{#              <button type="submit" class="btn btn-default">Pesquisar</button>#}
{#            </form>#}


            <ul class="nav navbar-nav">
              <li class="#"><a href="{%  url 'core:contato' %}">Contato</a></li>
            </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                      <a href="#" class="sair_menu dropdown-toggle" data-toggle="dropdown">Olá, {{user.username}}! </a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'accounts:conta'%}">Configurações </a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'accounts:mensagens' %}">Mensagens</a></li>
                        <li class="divider"></li>
                        <li><a href="{%  url 'accounts:logout' %}">Sair</a></li>
                      </ul>
                    </li>
                  </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="#"><a href="{%  url 'index:index' %}">Voltar ao Site!</a></li>
            </ul>


              {% endif %}

       </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </div>
    {% block content%}{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/accounts.js' %}"></script>
    <script src="{% static 'js/list_bagagem.js' %}"></script>
    <script src="{% static 'js/progresso.js' %}"></script>
    <script src="{% static 'js/entra_bagagem.js' %}"></script>

  </body>
</html>

clinica_das_malas/core/templates/inicio.html
{% extends 'home.html' %}
{% block content %}
{% load static%}

	{% if user.e_funcionario == False %}
<div class="container" style=" margin-left: 27%; margin-top: 10%;">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <span class="glyphicon glyphicon-bookmark"></span> Quick Shortcuts</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-6 col-md-6">
                          <a href="{% url 'bagagem:cliente' %}" class="btn btn-danger btn-lg" role="button"><span class="glyphicon glyphicon-list-alt"></span> <br/>Minhas Bagagens</a>
                          <a href="{% url 'tecnico:pesquisar' %}" class="btn btn-warning btn-lg" role="button"><span class="glyphicon glyphicon-bookmark"></span> <br/>Técnicos</a>
                          <a href="{% url 'accounts:mensagens' %}" class="btn btn-primary btn-lg" role="button"><span class="glyphicon glyphicon-comment"></span> <br/>Mensagens</a>
                        </div>
                        <div class="col-xs-6 col-md-6">
                          <a href="{% url 'accounts:conta' %}" class="btn btn-success btn-lg" role="button"><span class="glyphicon glyphicon-user"></span> <br/>Minha conta</a>
                          <a href="#" class="btn btn-info btn-lg" role="button"><span class="glyphicon glyphicon-file"></span> <br/>Delivery</a>
                          <a href="{% url 'core:contato' %}" class="btn btn-primary btn-lg" role="button"><span class="glyphicon glyphicon-picture"></span> <br/>Contato</a>
                        </div>
                    </div>
                    <a href="https://www.facebook.com/clinicadasmalas/" class="btn btn-success btn-lg btn-block" role="button"><span class="glyphicon glyphicon-globe"></span> Facebook</a>
                </div>
            </div>
        </div>
    </div>
</div>
	{% elif user.is_superuser == False%}
	<h1 style="color: white">Você é um operador! O que deve ter aqui?</h1>
	{% else %}

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>

<div class="container resumo_adm">  
  <div>
    <h2>Resumo Administrativo</h2>
  </div>
    <hr>
  <div class="col-md-6 quadro">
    <div class="titulo">
      <h4>Resumo de Vendas</h4>
    </div>
        <script type="text/javascript">      
          var ctx = document .getElementById( "myChart" ); 
          var ctx = document .getElementById( "myChart" ).getContext( "2d" ); 
          var ctx = $( "#myChart" ); 
          var ctx = "myChart"; 
        </script>
      <canvas id="myChart" width="100%" height= "50%"></canvas>
        <script> 
        var ctx = document .getElementById( "myChart" );
        var myChart = new Chart(ctx, { 
          type: 'bar' , 
          data: {  
            datasets: [{ 
              label: 'Nº de Vendas' , 
              data: [ 150 , 340 , 320 , 190 , 202 , 300 ],
              backgroundColor: [ 'rgba(30, 112, 201, 0.4)' ,'rgba(30, 112, 201, 0.4)' ,'rgba(30, 112, 201, 0.4)' ,'rgba(30, 112, 201, 0.4)' ,'rgba(30, 112, 201, 0.4)' ,'rgba(30, 112, 201, 0.4)'],
                }, {
              label: 'Nº de Atrasos',
              data: [30, 40, 10, 25, 12, 33],
              backgroundColor: ['rgba(236, 33, 44, 0.6)'],
              borderWidth:5,
              borderColor: ['rgba(255, 50, 50, 0.2)'],
              lineTension: 0,
              hitRadius: 5,

              type: 'line'}],
            labels: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho"]},
          options: { scales: { yAxes: [{ ticks: { beginAtZero: true } }] } } }); 
        </script> 
    </div>

    <div class="col-md-6 quadro">
      <div class="titulo">
        <h4>Resumo Financeiro</h4>
      </div>
          <script type="text/javascript">      
            var ctx = document .getElementById( "myLineChart" ); 
            var ctx = document .getElementById( "myLineChart" ).getContext( "2d" ); 
            var ctx = $( "#myLineChart" ); 
            var ctx = "myLineChart"; 
          </script>
        <canvas id="myLineChart" width="100%" height= "50%"></canvas>
          <script> 
          var ctx = document .getElementById( "myLineChart" );
            var myLineChart = new Chart(ctx, {
            type: 'line',
            data: { 
              labels: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho"],
              datasets: [{
                label: "Conta de Água", 
                data: [100 , 80, 120, 210, 20, 150],
                backgroundColor: ['rgba(30, 197, 62, 0.4)'],
                fill:false, borderColor: 'rgb(123, 432, 111)', lineTension:0.1
              }, {
                label: "Conta de Luz", 
                data: [150 , 180, 90, 110, 105, 50],
                 backgroundColor: ['rgba(30, 40, 215, 0.4)'],
                fill:false, borderColor: 'rgba(30, 40, 215, 0.4)', lineTension:0.1
                }]},
            options: { 
              scales: {
               yAxes: [{ticks: {beginAtZero: true,}}]
            }}
            });
          </script>
      </div>

      <div class="col-md-6 quadro">
          <div class="titulo">
            <h4>Ordens de Serviço por Técnico - MÊS</h4>
          </div>
          <script type="text/javascript">      
            var ctx = document .getElementById( "TecnicoChart" ); 
            var ctx = document .getElementById( "TecnicoChart" ).getContext( "2d" ); 
            var ctx = $( "#TecnicoChart" ); 
            var ctx = "TecnicoChart"; 
          </script>
        <canvas id="TecnicoChart" width="100%" height= "50%"></canvas>
          <script>
            var ctx = document .getElementById( "TecnicoChart" );
            var TecnicoChart = new Chart(ctx, { 
            type: 'horizontalBar' , 
            data: { labels: [ "Funcionário 1" , "Funcionário 2" , "Funcionário 3" , "Funcionário 4"], 
              datasets: [{ label: 'Nº de Ordens de Serviço - MÊS' , 
              data: [ 20 , 30 , 15 , 60],
              fill: false,
              backgroundColor: [ 'rgba(54, 362, 135, 0.5)' , 'rgba(54, 362, 135, 0.5)' , 'rgba(54, 362, 135, 0.5)' , 'rgba(54, 362, 135, 0.5)'],
              borderColor: ['rgba(54, 362, 135, 0.9)' , 'rgba(54, 362, 135, 0.9)' , 'rgba(54, 362, 135, 0.9)' , 'rgba(54, 362, 135, 0.9)'],
              borderWidth: 1}]            
            }, 
          options: { scales: { xAxes: [{ ticks: { beginAtZero: true } }] } } });
          </script>
      </div>
 
</div>

  <!--
		<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

	{# Script para criação do gráfico de fluxo de caixa #}
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      var monthNames = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
	      "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
      ];
      var dt = new Date();
      var month = dt.getMonth();

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Mês', 'Faturamento'],
          [monthNames[month-3],  {{ valor4 }}],
          [monthNames[month-2],  {{ valor3 }}],
          [monthNames[month-1],  {{ valor2 }}],
          [monthNames[month],  {{ valor1 }}],
        ]);

        var options = {
          title: 'Acompanhamento de Caixa',
          hAxis: {title: 'Mês',  titleTextStyle: {color: '#333'}},
          vAxis: {minValue: 0}
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
	<div id="chart_div" style="width: 70%; height: 500px; margin-left: 16%;" ></div>
  -->
	{% endif %}

{% endblock %}