clinica_das_malas/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from clinica_das_malas.accounts.views import register, conta, messages
from clinica_das_malas.settings import LOGOUT_URL

urlpatterns = [
    url(r'^entrar/', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^sair/', logout, {'next_page': LOGOUT_URL}, name='logout'),
    url(r'^cadastre-se/$', register, name='register'),
    url(r'^mensagens/$', messages, name='mensagens'),
    url(r'^$', conta, name ='conta'),
]

clinica_das_malas/bagagem/urls.py
from django.conf.urls import url
from .views import list_bagagens, show_bagagem, entra_bagagem, cliente_bagagens

urlpatterns = [
    url(r'^$', list_bagagens, name="list"),
    url(r'^(\d+)', show_bagagem, name="show"),
    url(r'^entra/$', entra_bagagem, name="entra_bagagem"),
    url(r'^cliente/$', cliente_bagagens, name="cliente"),
]

clinica_das_malas/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from clinica_das_malas.core.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^conta/', include('clinica_das_malas.accounts.urls', namespace="accounts")),
    url(r'^', include('clinica_das_malas.core.urls', namespace="core")),
    url(r'^bagagens/', include('clinica_das_malas.bagagem.urls', namespace="bagagem")),
    url(r'^estoque/', include('clinica_das_malas.produto.urls', namespace="produto")),
    url(r'^index/', include('clinica_das_malas.index.urls', namespace="index")),
    url(r'^tecnico/', include('clinica_das_malas.tecnico.urls', namespace="tecnico"))
]

clinica_das_malas/bagagem/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import User

from clinica_das_malas.tecnico.models import Tecnico
from clinica_das_malas.tipoServico.models import TipoServico
from clinica_das_malas.accounts.models import User


class Bagagem(models.Model):
    TIPO_BAGAGENS = (
    ('B', 'Bolsa'),
    ('M', 'Mala')
    )

    TIPO_MALA = (
    ('F', 'Flexível'),
    ('S', 'Semi-rígida'),
    ('R', 'Rígida')
    )

    TAMANHOS = (
    ('P', 'Pequena'),
    ('M', 'Média'),
    ('G', 'Grande')
    )

    MODELOS = (
    ('N', 'Normal'),
    ('3', '360')
    )

    cliente = models.ForeignKey(User)

    tipo_bagagem = models.CharField(
    max_length = 1,
    choices=TIPO_BAGAGENS
    )
    marca = models.CharField(max_length = 30)
    cor = models.CharField(max_length = 20)
    tipo_mala = models.CharField(
        max_length = 1,
        choices = TIPO_MALA
        )
    tamanhos = models.CharField(
        max_length = 1,
        choices = TAMANHOS
        )
    modelos = models.CharField(
        max_length = 1,
        choices = MODELOS
        )
    tipo_servicos = models.ManyToManyField(TipoServico)
    prazo = models.IntegerField()
    observacoes = models.TextField(blank=True, null=True)
    tecnico = models.ForeignKey(Tecnico, null=True)

    concluida = models.BooleanField(default=False)

    created_at = models.DateTimeField('Criado em', auto_now_add=True) #Atualiza sempre que for criado
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.cliente.username + " - " + self.marca + ' - ' + self.cor

    def get_future_date(self):
        futuro = date.fromordinal(self.created_at.toordinal()+self.prazo)
        return futuro

    def get_valor(self):
        servicos = self.tipo_servicos.all()
        total = 0
        for servico in servicos:
            total += servico.valor
        return total

    def get_status(self):
        if self.concluida:
            return 'pronto'
        elif date.today() > self.get_future_date():
            return 'atrasado'
        else:
            return 'pendente'

    class Meta:
        ordering = ['created_at']

clinica_das_malas/bagagem/forms.py
from django import forms

from clinica_das_malas.bagagem.models import Bagagem


class BagagemForm(forms.ModelForm):

    class Meta:
        model = Bagagem
        fields = ('cliente', 'tipo_bagagem', 'marca', 'cor', 'tipo_mala', 'tamanhos', 'modelos', 'tipo_servicos', 'prazo',
                  'observacoes', 'tecnico')

clinica_das_malas/bagagem/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse

from clinica_das_malas.bagagem.models import Bagagem
from django.contrib.auth.decorators import login_required
from clinica_das_malas.bagagem.forms import BagagemForm


from clinica_das_malas.tipoServico.models import TipoServico


@login_required()
def list_bagagens(request):
    bagagens = Bagagem.objects.all()
    context = {
        'bagagens': bagagens
    }
    return render(request, 'list_bagagens.html', context)

@login_required()
def show_bagagem(request, pk):
    bagagem = get_object_or_404(Bagagem, pk=pk)
    servicos = bagagem.tipo_servicos.all()
    total = 0
    for servico in servicos:
        total += servico.valor
    context = {
        'bagagem': bagagem,
        'servicos': servicos,
        'total': total
    }
    return render(request, 'show_bagagem.html', context)


@login_required()
def cliente_bagagens(request):
    bagagens = Bagagem.objects.filter(cliente=request.user)
    user = request.user
    context = {'bagagens':bagagens,
               'user':user}
    return render(request, 'cliente_bagagens.html', context)


@login_required()
def entra_bagagem(request):
    template_name = 'entra_bagagem.html'
    tipos = TipoServico.objects.all()
    if request.method == 'POST':
        form = BagagemForm(request.POST)
        print(form.errors)
        if form.is_valid():
            print('olha que entrou')
            bagagem = form.save()
            bagagem.save()

    else:
        form = BagagemForm()
    context = {
        'form': form,
        'tipos': tipos
    }

    return render(request, template_name, context)

clinica_das_malas/bagagem/templates/cliente_bagagens.html
{% extends 'home.html' %}
{% block content %}

    <div class="container">
	<div class="row-fluid">

		<section class="content">
		{% if user.e_funcionario == False %}
			<div class="">
				<div class="panel panel-default">
                		<h1>Lista de Bagagens</h1>
					<div class="panel-body">
                    {% if bagagens %}
						<div class="pull-right">
							<div class="btn-group">
								<button type="button" class="btn btn-success btn-filter" data-target="pronto">Pronto</button>
								<button type="button" class="btn btn-warning btn-filter" data-target="pendente">Pendente</button>
								<button type="button" class="btn btn-danger btn-filter" data-target="atrasado">Atrasado</button>
								<button type="button" class="btn btn-default btn-filter" data-target="all">Todos</button>
							</div>
						</div>
                    <div class="table-container">

<table id="mytable" class="table table-bordred table-striped" style="text-align: center; margin-top: 10%;">

                   <thead>
                   <th style="text-align: center">Tecnico Responsável</th>
                   <th style="text-align: center">Marca</th>
                   <th style="text-align: center">Cor</th>
                   <th style="text-align: center">Data de Entrega</th>
                {% endif %}
                   </thead>
    <tbody>


    {% for bagagem in bagagens %}
        <tr data-status="{{ bagagem.get_status }}" onClick='return minhaFuncaoOnClick({{ bagagem.pk }});' onMouseOver='return minhaFuncaoOnMouseOver(this);' onMouseOut='return minhaFuncaoOnMouseOut(this);'>
            <td>{{ bagagem.cliente.username }}</td>
            <td>{{ bagagem.marca }}</td>
            <td>{{ bagagem.cor }}</td>
            <td>{{ bagagem.get_future_date }} </td>
        </tr>
    {% empty %}
            <tr>
                <td><div class="alert alert-danger" role="alert">Nenhuma bagagem cadastrada!</div></td>
            </tr>

    {% endfor %}

    </tbody>

</table>
						</div>
					</div>
				</div>
			</div>
		</section>
		{% else %}
			<div class="alert alert-danger" role="alert">Página exclusiva para clientes!</div>
		{% endif %}
	</div>
</div>
    <script language='javascript' type='text/javascript'>
       function minhaFuncaoOnClick(pk){
            window.location.href='/bagagens/'+pk;
       }
       function minhaFuncaoOnMouseOver(objTR){
            objTR.style.background='#DDDDDD';
       }

       function minhaFuncaoOnMouseOut(objTR){
            objTR.style.background='#FFFFFF';
       }

    </script>

{% endblock %}

clinica_das_malas/bagagem/templates/entra_bagagem.html
{% extends 'home.html' %}
{% load widget_tweaks %}
{% load static%}
{% block content %}

	<style type="text/css">
		SELECT, INPUT[type="text"] {
		    width: 160px;
		    box-sizing: border-box;
		}
		SECTION {
		    padding: 8px;
		    background-color: ghostwhite;
		    overflow: auto;
        border-radius: 10px;
		}
		SECTION > DIV {
		    float: left;
		    padding: 4px;
		}
		SECTION > DIV + DIV {
		    width: 40px;
		    text-align: center;
		}
	</style>
<div class="container">
		<section>
        <div class="wizard">
            <div class="wizard-inner">
                <div class="connecting-line"></div>
                <ul class="nav nav-tabs" role="tablist">

                    <li role="presentation" class="active">
                        <a href="#step1" data-toggle="tab" aria-controls="step1" role="tab" title="Step 1">
                            <span class="round-tab">
                                <i class="glyphicon glyphicon-user"></i>
                            </span>
                        </a>
                    </li>
                    <li role="presentation" class="disabled">
                        <a href="#step2" data-toggle="tab" aria-controls="step2" role="tab" title="Step 2">
                            <span class="round-tab">
                                <i class="glyphicon glyphicon-briefcase"></i>
                            </span>
                        </a>
                    </li>
                    <li role="presentation" class="disabled">
                        <a href="#step3" data-toggle="tab" aria-controls="step3" role="tab" title="Step 3">
                            <span class="round-tab">
                                <i class="glyphicon glyphicon-wrench"></i>
                            </span>
                        </a>
                    </li>
                    <li role="presentation" class="disabled">
                        <a href="#complete" data-toggle="tab" aria-controls="complete" role="tab" title="Complete">
                            <span class="round-tab">
                                <i class="glyphicon glyphicon-ok"></i>
                            </span>
                        </a>
                    </li>
                </ul>
            </div>

            <form class="form-horizontal" id="form1" action="#" method="post">
                {% csrf_token %}
                <div class="tab-content">
                    <div class="tab-pane active" role="tabpanel" id="step1">

                        <h2 style="font-family: Times">Selecione o Cliente</h2>
                        <br>
                        <div class="form-group">
                          <label for="cliente" class="col-sm-2 control-label">Cliente</label>
                          <div class="col-sm-10">
                            <select class="form-control">
                              {% for field in form.cliente %}
                                  <option value="" disabled selected hidden> - Selecione - </option>
                                  <option value='{{ field }}'></option>
                              {% endfor %}
                            </select>
                            <a class="btn" href="{% url 'accounts:register' %}">+ Novo</a>
                          </div>
                        </div>
                        <br>
                        <ul class="list-inline pull-right">
                            <li><button type="button" class="btn btn-primary next-step" >Continuar</button></li>
                        </ul>
                    </div>
                    <div class="tab-pane" role="tabpanel" id="step2">
                        <h2 style="font-family: Times">Características do Objeto</h2>
                        <br>
                        <div class="form-group">
                          <label for="tipo_bagagem" class="col-sm-2 control-label">Tipo de Bagagem</label>
                          <div class="col-sm-10">
                            <select class="form-control">
                                      {% for field in form.tipo_bagagem %}
                                          <option value="" disabled selected hidden> - Selecione - </option>
                                          <option value='{{ field }}'></option>
                                      {% endfor %}
                            </select>
                          </div>
                        </div>
                        <br>
                        <div class="form-group">
                          <label for="tipo_mala" class="col-sm-2 control-label">Tipo de Mala</label>
                          <div class="col-sm-10">
                            <select class="form-control">
                                      {% for field in form.tipo_mala %}
                                          <option value="" disabled selected hidden> - Selecione - </option>
                                          <option value='{{ field }}'></option>
                                      {% endfor %}
                            </select>
                          </div>
                        </div>
                        <br>
                        <div class="form-group">
                          <label for="marca" class="col-sm-2 control-label">Marca</label>
                          <div class="col-sm-10">
                            <input type="text" class="form-control" id="id_marca" placeholder="...">
                          </div>
                        </div>
                        <br>
                        <div class="form-group">
                          <label for="cor" class="col-sm-2 control-label">Cor</label>
                          <div class="col-sm-10">
                            <input type="text" class="form-control" id="id_cor" placeholder="...">
                          </div>
                        </div>
                        <br>
                        <div class="form-group">
                          <label for="tamanhos" class="col-sm-2 control-label">Tamanhos</label>
                          <div class="col-sm-10">
                            <select class="form-control">
                                      {% for field in form.tamanhos %}
                                          <option value="" disabled selected hidden> - Selecione - </option>
                                          <option value='{{ field }}'></option>
                                      {% endfor %}
                            </select>
                          </div>
                        </div>
                        <br>
                        <div class="form-group">
                          <label for="modelos" class="col-sm-2 control-label">Modelo</label>
                          <div class="col-sm-10">
                            <select class="form-control">
                                      {% for field in form.modelos %}
                                          <option value="" disabled selected hidden> - Selecione - </option>
                                          <option value='{{ field }}'></option>
                                      {% endfor %}
                            </select>
                          </div>
                        </div>
                        <br>
                        <ul class="list-inline pull-right">
                            <li><button type="button" class="btn btn-default prev-step">Voltar</button></li>
                            <li><button type="button" class="btn btn-primary next-step">Continuar</button></li>
                        </ul>
                    </div>

                    <div class="tab-pane" role="tabpanel" id="step3">
                      <h2 style="font-family: Times">Tipos de Serviço</h2><br>
                      <div class="form-group">
                        <label for="tipo_servicos" class="col-sm-2 control-label">Tipos de Serviço:</label>
                        <section class="container">
						    <div>
						        <select id="leftValues" size="5" multiple></select>
						    </div>
						    <div>
						        <input type="button" id="btnLeft" value="&lt;&lt;" />
						        <input type="button" id="btnRight" value="&gt;&gt;" />
						    </div>
						    <div>
						        <select id="rightValues" size="{{ tipos.length }}" multiple>
						            {% for tipo in tipos %}
							        <option>{{ tipo.nome }}</option>
							        {% endfor %}
						        </select>
						        <div>
						            <input type="text" id="txtRight" />
						        </div>
						    </div>
						</section>
                      </div>
                      <div class="form-group">
                        <label for="tecnico" class="col-sm-2 control-label">Técnico:</label>
                        <div class="col-sm-10">
                          <select class="form-control">
                                    {% for field in form.tecnico %}
                                        <option value="" disabled selected hidden> - Selecione - </option>
                                        <option value='{{ field }}'></option>
                                    {% endfor %}
                          </select>
                        </div>
                      </div>
                          <ul class="list-inline pull-right">
                              <li><button type="button" class="btn btn-default prev-step">Voltar</button></li>
                              <li><button type="button" class="btn btn-primary btn-info-full next-step">Continuar</button></li>
                          </ul>
                          <p>Alguma observacao?</p>
                    </div>

                    <div class="tab-pane" role="tabpanel" id="complete">
                        <h3>Concluído</h3>
                            <div class="form-group">
                            <div class="col-md-12 text-right">
                              <button type="submit" form="form1" class="btn btn-primary btn-lg">Enviar</button>
                            </div>
                          </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </form>
        </div>
    </section>
</div>

{% endblock content %}

clinica_das_malas/bagagem/templates/list_bagagens.html
{% extends 'home.html' %}
{% block content %}

<div class="container">
	<div class="row-fluid espaco">
		<section class="content">
				<div class="panel panel-default">
                		<h1>Lista de Bagagens</h1>
					<div class="panel-body">
          {% if bagagens %}
						<div class="pull-right">
							<div class="btn-group">
								<button type="button" class="btn btn-success btn-filter" data-target="pronto">Pronto</button>
								<button type="button" class="btn btn-warning btn-filter" data-target="pendente">Pendente</button>
								<button type="button" class="btn btn-danger btn-filter" data-target="atrasado">Atrasado</button>
								<button type="button" class="btn btn-default btn-filter" data-target="all">Todos</button>
							</div>
						</div>
						<div class="table-container">

            <table id="mytable" class="table table-bordred table-striped" style="text-align: center; margin-top: 10%;">

                  <thead>
                    <th class="coluna_bag">Cliente</th>
                    <th class="coluna_bag">Marca</th>
                    <th class="coluna_bag">Cor</th>
                    <th class="coluna_bag">Data de Entrega</th>         
                  </thead>
          {% endif %}

                  <tbody>
          {% for bagagem in bagagens %}
                    <tr onClick='return minhaFuncaoOnClick({{ bagagem.pk }});' onMouseOver='return minhaFuncaoOnMouseOver(this);' onMouseOut='return minhaFuncaoOnMouseOut(this);'>
                        <td data-status="{{ bagagem.get_status }}">
                          {{ bagagem.cliente.username }}</td>
                        <td data-status="{{ bagagem.get_status }}">
                          {{ bagagem.marca }}</td>
                        <td data-status="{{ bagagem.get_status }}">
                          {{ bagagem.cor }}</td>
                        <td data-status="{{ bagagem.get_status }}">
                          {{ bagagem.get_future_date }} </td>
                    </tr>
          {% empty %}
                    <tr>
                        <td><div class="alert alert-danger" role="alert">Nenhuma bagagem cadastrada!</div></td>
                    </tr>
          {% endfor %}
                  </tbody>

            </table>
						</div>
					</div>
				</div>
		</section>
	</div>
</div>
    <script language='javascript' type='text/javascript'>
       function minhaFuncaoOnClick(pk){
            window.location.href='/bagagens/'+pk;
       }
       function minhaFuncaoOnMouseOver(objTR){
            objTR.style.background='#DDDDDD';
       }

       function minhaFuncaoOnMouseOut(objTR){
            objTR.style.background='#FFFFFF';
       }

    </script>

{% endblock %}

clinica_das_malas/bagagem/templates/show_bagagem.html
{% extends 'home.html' %}
{% block content %}

<div class="container" style="background: white">
    <div class="row">
        <div class="col-xs-12">
    		<div class="invoice-title">
    			<h2>Detalhes da Bagagem</h2>
                <h3 class="pull-right" style="font-style: italic">Ordem de Serviço:
                #{{ bagagem.id }}
                </h3>
    		</div>
    		<hr>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
    				<strong>CLIENTE</strong><br>
    					<p>Nome: {{ bagagem.cliente.get_full_name }}<br>
    					Usuário: {{ bagagem.cliente.username }}<br>
    					Endereço: {{ bagagem.cliente.endereco }}<br>
    					Telefone:{{ bagagem.cliente.telefone }}
                        </p>
    				</address>
    			</div>
    			<div class="col-xs-6 text-right">
                     <address>
                        <p style="font-weight: bold; color: #002266">{{ bagagem.created_at }}</p><br>
                    </address>
    			</div>
    		</div>
    		<div class="row">
    			<div class="col-xs-6">
    				<address>
                    <strong>BAGAGEM ({{ bagagem.get_tipo_bagagem_display }})</strong><br>
                        <p>Tipo: {{ bagagem.get_tipo_mala_display }}<br>
                        Marca: {{ bagagem.marca }}<br>
                        Cor: {{ bagagem.cor }}<br>
                        Tamanho: {{ bagagem.get_tamanhos_display }}<br>
                        Modelo: {{ bagagem.get_modelos_display }}<br>
                        </p>
                    </address>
    			</div>
    			<div class="col-xs-6 text-right">
    				<address><br>
                    <strong>Outras Informações:</strong><br>
                        <p>Aqui ficarão todas as outras informações de cadastro referentes à mala cadastrada. Qualquer informação que seja relevante!
                        </p>
                    </address>
    			</div>
    		</div>
    	</div>
    </div>

    <div class="row">
    	<div class="col-md-12">
    		<div class="panel panel-default">
    			<div class="panel-heading">
    				<h3 class="panel-title"><strong>Serviços</strong></h3>
    			</div>
    			<div class="panel-body">
    				<div class="table-responsive">
    					<table class="table table-condensed">
    						<thead>
                                <tr>
        							<td><strong>Item</strong></td>
        							<td class="text-center"><strong>Descrição</strong></td>
        							<td class="text-center"><strong>Valor</strong></td>
        							<td class="text-right" style="font-size: large;"><strong>Total</strong></td>
                                </tr>
    						</thead>
    						<tbody>

    							<!-- foreach ($order->lineItems as $line) or some such thing here -->
                                {% for servico in servicos %}
                                    <tr>
                                        <td>{{servico.nome}}</td>
                                        <td class="text-center">{{ servico.descricao }}</td>
                                        <td class="text-center">R$ {{ servico.valor }}</td>
                                        <td class="text-right"></td>
                                    </tr>
                                {% empty %}
                                        <td class="text-right">0</td>
    							{% endfor %}
                                    <tr>
                                        <td></td>
                                        <td class="text-center"></td>
                                        <td class="text-center"></td>
                                        <td class="text-right" style="color: red; font-size: x-large; font-weight: 800;">{{ total }}</td>
                                    </tr>


    						</tbody>
    					</table>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>

{% endblock content %}